version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${JDBC_USER}
      POSTGRES_PASSWORD: ${JDBC_PASSWORD}
      POSTGRES_DB: ${JDBC_DB}
    ports:
      - "5432:5432"